/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexaobd.bd;
import conexaobd.MostrarTabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class cadastroCliente extends javax.swing.JFrame {

    bd conexao = new bd();
    private String Pesquisa;
    
    
    public cadastroCliente() {
        initComponents();
        conexao.conecta();
        preencherTabela("SELECT * FROM cliente ORDER BY id_cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        idade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        end = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        municipio = new javax.swing.JTextField();
        uf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cad = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pesquisa = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHOP");
        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(800, 850));
        setMinimumSize(new java.awt.Dimension(800, 850));
        setPreferredSize(new java.awt.Dimension(800, 850));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 60, 60, 26);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Idade");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 60, 60, 26);

        nome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nome.setPreferredSize(new java.awt.Dimension(92, 30));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel1.add(nome);
        nome.setBounds(120, 60, 240, 30);

        idade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        idade.setPreferredSize(new java.awt.Dimension(92, 30));
        jPanel1.add(idade);
        idade.setBounds(490, 60, 140, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Endereço");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 80, 26);

        end.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        end.setPreferredSize(new java.awt.Dimension(92, 30));
        jPanel1.add(end);
        end.setBounds(120, 100, 240, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Nº");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 100, 34, 26);

        num.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        num.setPreferredSize(new java.awt.Dimension(92, 30));
        jPanel1.add(num);
        num.setBounds(490, 100, 140, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Bairro");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 150, 50, 26);

        bairro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bairro.setPreferredSize(new java.awt.Dimension(92, 30));
        jPanel1.add(bairro);
        bairro.setBounds(120, 150, 240, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("CEP");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 150, 32, 26);

        cep.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cep.setPreferredSize(new java.awt.Dimension(92, 30));
        jPanel1.add(cep);
        cep.setBounds(490, 150, 140, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Municipio");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 190, 80, 20);

        municipio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        municipio.setPreferredSize(new java.awt.Dimension(92, 30));
        jPanel1.add(municipio);
        municipio.setBounds(120, 190, 240, 30);

        uf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        uf.setPreferredSize(new java.awt.Dimension(92, 30));
        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });
        jPanel1.add(uf);
        uf.setBounds(490, 190, 140, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("UF");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 190, 34, 26);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        cad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cad.setText("Cadastrar");
        cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadActionPerformed(evt);
            }
        });
        jPanel2.add(cad);
        cad.setBounds(50, 40, 150, 25);

        edit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edit.setText("Editar");
        edit.setEnabled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit);
        edit.setBounds(290, 40, 150, 25);

        del.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        del.setText("Excluir");
        del.setEnabled(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel2.add(del);
        del.setBounds(520, 40, 150, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 269, 740, 110);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 420, 20, 26);

        pesquisa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisa.setPreferredSize(new java.awt.Dimension(92, 30));
        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(pesquisa);
        pesquisa.setBounds(70, 420, 450, 30);

        pesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(pesquisar);
        pesquisar.setBounds(550, 420, 150, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 10, 740, 510);

        tableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 560, 460, 240);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        
        
    }//GEN-LAST:event_pesquisaActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadActionPerformed
        conexao.conecta();
        try{
            PreparedStatement pst = conexao.conex.prepareStatement("INSERT INTO cliente(nome,endereco,bairro,municipio,idade,num,cep,uf)VALUES(?,?,?,?,?,?,?,?)");
            pst.setString(1, nome.getText());
            pst.setString(2, end.getText());
            pst.setString(3, bairro.getText());
            pst.setString(4, municipio.getText());
            pst.setString(5, idade.getText());
            pst.setString(6, num.getText());
            pst.setString(7, cep.getText());
            pst.setString(8, uf.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
            nome.setText("");
            end.setText("");
            bairro.setText("");
            municipio.setText("");
            idade.setText("");
            num.setText("");
            cep.setText("");
            uf.setText("");
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro! Cadastro não efetuado."+ex.toString());
        }
        conexao.desconecta();
    }//GEN-LAST:event_cadActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        conexao.conecta();
        conexao.executaSQL("SELECT * FROM cliente WHERE id_cliente ="+pesquisa.getText());
        try {
            conexao.rs.first();
            nome.setText(conexao.rs.getString("nome"));
            end.setText(conexao.rs.getString("endereco"));
            bairro.setText(conexao.rs.getString("bairro"));
            municipio.setText(conexao.rs.getString("municipio"));
            idade.setText(conexao.rs.getString("idade"));
            num.setText(conexao.rs.getString("num"));
            cep.setText(conexao.rs.getString("cep"));
            uf.setText(conexao.rs.getString("uf"));
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro ao localizar registro!"+ex);
        }
       // pesquisa.setText("");
        del.setEnabled(true);
        edit.setEnabled(true);
        conexao.desconecta();
    }//GEN-LAST:event_pesquisarActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja remover o registro?");
        if (resposta == JOptionPane.YES_OPTION) {
            conexao.conecta();
            try {
                PreparedStatement pst = conexao.conex.prepareStatement("DELETE FROM cliente WHERE id_cliente=?");
                pst.setString(1, pesquisa.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registro excluido com sucesso!");
            } catch(SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro! Remoção de dados não efetuada."+ex.toString());
            }
            pesquisa.setText("");
            nome.setText("");
            end.setText("");
            bairro.setText("");
            municipio.setText("");
            idade.setText("");
            num.setText("");
            cep.setText("");
            uf.setText("");
        }
       conexao.desconecta();
    }//GEN-LAST:event_delActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        conexao.conecta();
        try{
            PreparedStatement pst = conexao.conex.prepareStatement("UPDATE cliente SET nome=?, endereco=?, bairro=?, municipio=?, idade=?, num=?, cep=?, uf=?  WHERE id_cliente=?");
            pst.setString(9, pesquisa.getText());
            pst.setString(1, nome.getText());
            pst.setString(2, end.getText());
            pst.setString(3, bairro.getText());
            pst.setString(4, municipio.getText());
            pst.setString(5, idade.getText());
            pst.setString(6, num.getText());
            pst.setString(7, cep.getText());
            pst.setString(8, uf.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Atualização efetuado com sucesso!");
            nome.setText("");
            end.setText("");
            bairro.setText("");
            municipio.setText("");
            idade.setText("");
            num.setText("");
            cep.setText("");
            uf.setText("");
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro! Atualização não efetuado."+ex.toString());
        }
        conexao.desconecta();
    }//GEN-LAST:event_editActionPerformed
    
    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"id_cliente","nome","municipio"};
        conexao.conecta();
        conexao.executaSQL(Sql);
        
        try{
            conexao.rs.first();
            
            do{
                dados.add(new Object[]{conexao.rs.getString("id_cliente"), conexao.rs.getString("nome"), conexao.rs.getString("municipio")});
            }while(conexao.rs.next());
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ARRAYLIST"+ex);
        }
        
        MostrarTabela tabela = new MostrarTabela(dados, colunas);
        tableList.setModel(tabela);
        tableList.getColumnModel().getColumn(0).setPreferredWidth(50);
        tableList.getColumnModel().getColumn(0).setResizable(false);
        tableList.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableList.getColumnModel().getColumn(1).setResizable(false);
        tableList.getColumnModel().getColumn(2).setPreferredWidth(200);
        tableList.getColumnModel().getColumn(2).setResizable(false);
        tableList.setAutoResizeMode(tableList.AUTO_RESIZE_OFF);
        tableList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JButton cad;
    private javax.swing.JTextField cep;
    private javax.swing.JButton del;
    private javax.swing.JButton edit;
    private javax.swing.JTextField end;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField municipio;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField num;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTable tableList;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables

}
    

